### ISSUE TITLE
Tidal Hi-Fi spamming DNS request

### ISSUE THREAD

**Issue by kiiw** [flathub/com.mastermindzh.tidal-hifi#13]
Hi, i've noticed that the flatpak app spamms DNS request, while if i use it from browser it barely does any. (Over 70k in less than 24h)
It does DNS request even while there's not any music playing.
![immagine](https://github.com/flathub/com.mastermindzh.tidal-hifi/assets/7533941/c7c7ec45-ac7c-493a-a9f0-8376271a196a)
In this screenshot You can see that until 11:40 i was using the flatpak app, then after 11:40 i was using the browser based webplayer and the DNS are significantly reduced.
I don't know if it's normal or not.

**Comment by Mar0xy** [comment]
This was once opened on the main repo and closed due to not having any
control over it https://github.com/Mastermindzh/tidal-hifi/issues/163

**Comment by Mastermindzh** [comment]
![image](https://github.com/flathub/com.mastermindzh.tidal-hifi/assets/4190290/da4eebd6-e882-45b9-b500-6a432c2a58df)

I too have this problem, but we have very little control over it.
It seems to do a lot of requests to stream media (pics, music, etc)

sorry!
