### ISSUE TITLE
Why is it called "Rick van Lieshout" in flatpak list?

### ISSUE THREAD

**Issue by KaelWD** [flathub/com.mastermindzh.tidal-hifi#22]
Everything else uses the actual package name not the name of the author:

![Screenshot_20240306_135211](https://github.com/flathub/com.mastermindzh.tidal-hifi/assets/16421948/42cecb1b-015c-4f81-91b3-3e6696c90252)

**Comment by Mastermindzh** [comment]
Good question. I'd have to ask @Mar0xy if there's a specific reason but I think it's just a small mistake :)

@Mar0xy any specific reason?

**Comment by Mar0xy** [comment]
It's a bug on Flatpak's side

https://github.com/flatpak/flatpak/issues/5700
